baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ingrid Olea"
theme = "hallo"
publishDir = "docs"
[Author]
	name = "Ingrid Olea"
[params]
	[[params.links]]
		iconset = "fas"
		icon = "envelope"
		title = "email"
		url = "mailto:ingrid_olea@hks.harvard.edu"

	[[params.links]]
		icon = "linkedin"
		title = "LinkedIn"
		url = "https://www.linkedin.com/in/ingrid-olea-583bb019/"	

	[[params.links]]
		icon = "twitter"
		title = "Twitter"
		url = "https://twitter.com/ingridelena/"

	[[params.links]]
		icon = "github"
		title = "Github"
		url = "https://github.com/ingridolea"

	[[params.links]]
		iconset = "fas"
		icon = "file-pdf"
		title = "CV"
		url = "images/Olea_Ingrid_Resume_250120.pdf"

    [[params.links]]
        iconset = "fas"
        icon = "info-circle"
        title = "Additional information"
        url = "#info"

	[params.colors]
		background = "#900C3F"
		foreground = "#edf7ff"
		hover = "#ffba82"
